language:
  node_js
node_js:
  - 0.10

env:
  global:
    - GH_OWNER: GoogleCloudPlatform
    - GH_PROJECT_NAME: gcloud-node
script:
  - npm run lint
  - npm run test
after_success: ./scripts/build.sh
  #- git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
  #- cd site
  #- if git checkout gh-pages; then git checkout -b gh-pages; fi
  #- git rm -r .
  #- cp -R ../docs/* .
  #- cp ../docs/.* .
  #- git add -f .
  #- git config user.email "sawchuk@gmail.com"
  #- git config user.name "stephenplusplus"
  #- git commit -am "building gh-pages [ci skip]"
  #- git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1

