language: node_js
node_js:
- 0.10
env:
  global:
  - GH_OWNER: GoogleCloudPlatform
  - GH_PROJECT_NAME: gcloud-node
before_install:
- openssl aes-256-cbc -K $encrypted_170d47c2ec84_key -iv $encrypted_170d47c2ec84_iv
  -in key.json.enc -out key.json -d
script:
- npm run lint
- npm run test
after_success: ./scripts/regression.sh
before_deploy: ./scripts/release.sh
deploy:
  provider: npm
  email: silvano.luciani@gmail.com
  api_key:
    secure: EP4BMb603j4BTYVhWTA0yYgAJBbiCEwXj5zXIg1+oWuW9ivIDMOFbnPnwmTrMOnrNcs36YZ7PGaKEEsTMr9O0V7ifXLuS5qXAk8FByK7+2KAngmL5lkC/RQlLoQFY7j0LmNgVefk0FfAst75lJtYlTpLVHx4c3/2c2SUXw0048w=
  on:
    tags: true
    repo: silvolu/gcloud-node
    branch: travis-reg
